dependencies:
 - codecov
 # testing
 - mock
 - paste
 - pymemcache
 - pytest
 - pytest-cov
 - pytest-runner
 # WMS Requests, httpx was found to leak memory :(
 - requests
 - requests-mock
 # testing
 - werkzeug
